# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1a0d858aa0745e960ec50e986dbb03d34befbb2f38fed3673a7e4eb20ef4c47a983dc25f4fc251767bf4b56099e16e1e572075aa24c63cea4c40f624567f85

test:
  secret_key_base: b09612cee2e6480b6a93958fc968409a6712fa35b839cbcbe8838cfa82bbaf17020bcd666eeaa91a90ba6ed86563e50ad1fa96422274770881942e0c5ecea6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
